### ISSUE TITLE
Publish on the public store

### ISSUE THREAD

**Issue by jocado** [xnox/graphics-core22-samples#1]
Hi @xnox - apologies for initially creating this in the wrong place :)

This snap doesn't seem to be available on the public store. I would like to validate the nvidia-assemble is working on UC22.

Should it be published, or is it planned to be ?

**Comment by jocado** [comment]
```
$ snap info graphics-core22-samples
error: no snap found for "graphics-core22-samples"
```

**Comment by xnox** [comment]
This one is currently failing to build from source and we are working to SRU packaging changes in .deb Ubuntu Jammy to become buildable. I guess I should make a temporary PPA to at least get one build of this out.

**Comment by jocado** [comment]
If that's possible, and the alternative is a long wait, then I think that would be useful :+1:

**Comment by jocado** [comment]
@xnox Can you give me any details on the packaging changes required ?

**Comment by xnox** [comment]
> @xnox Can you give me any details on the packaging changes required ?

it will be part of the next SRU of nvidia drivers packaging in Ubuntu, specifically this change https://github.com/tseliot/nvidia-graphics-drivers/commit/7cb2fb031ecc4d14fb982af10e5f43a91650b3be

**Comment by jocado** [comment]
ok, thanks for info, doesn't seem like I can build locally in that case even.

Unless there's another way, I will revert back to uc20 for testing for now.

Thanks.

**Comment by xnox** [comment]
indeed more changes were needed, i have temporarily created a PPA until all of the provides are fixed up correctly, and pushed the snapcraft.yaml to use that forked PPA. it seems to build correctly but i haven't tested the resulting snap itself. I have released to latest/stable channel, so please try using graphics-core22-samples from the snapstore and let me know if that works for you. Thanks.

**Comment by jocado** [comment]
Great - thanks.  I will try and revert back to core22 for testing, and report back :+1:

**Comment by jocado** [comment]
@xnox Just FYI - this is working well, thanks very much.

Slight side note - looking at the output of snappy-debug, it seems like this snap could probably be made to work without devmode by adding the following interface plugs:
- `network-bind`
- `kernel-module-observe`
- `hardware-observe`

I haven't proposed an MR, as probably you have reasons for just leaving it as devmod required for now :slightly_smiling_face:

**Comment by xnox** [comment]
> @xnox Just FYI - this is working well, thanks very much.
> 
> Slight side note - looking at the output of snappy-debug, it seems like this snap could probably be made to work without devmode by adding the following interface plugs:
> 
> * `network-bind`
> * `kernel-module-observe`
> * `hardware-observe`
> 
> I haven't proposed an MR, as probably you have reasons for just leaving it as devmod required for now slightly_smiling_face

do i need those on interface plugs on the nvidia-assemble snap, the nvidia-core22 content provider, or on this graphics-core22-samples snap or everywhere? I will try to play around with this and make it work, because yes, ideally they would work fully confined without devmode needed.

**Comment by jocado** [comment]
I'm just referring to samples snap initially.

My testing is a bit limited, as I'm not working with a display, so I'm only able to run:
- `bandwidthTest`
- `deviceQuery`
- `eglinfo`

It looks like, the bare minimum extra interfaces plugs required to make them functional is only `network-bind`.  I hacked that into the snap, re-squashed, and connected the interface, and the utils seemed functional [ no errors ].

If you want to remove all audit logs then you would have to add the other two mentioned above, and it looks like perhaps `network-control` too.

I don't think anything is required on the content snap.

I suspect that the nvidia-assemble snap would bit a bit more tricky to get working with standard builtin interfaces, because of the udev access.  I'd more more than happy to work with you getting nvidia-assemble working without devmode, because we are keen use nvidia support.  Shall I open a bug about it over in https://github.com/xnox/nvidia-assemble for discussion ?

**Comment by xnox** [comment]
> I'm just referring to samples snap initially.
> 
> My testing is a bit limited, as I'm not working with a display, so I'm only able to run:
> 
> * `bandwidthTest`
> * `deviceQuery`
> * `eglinfo`
> 
> It looks like, the bare minimum extra interfaces plugs required to make them functional is only `network-bind`. I hacked that into the snap, re-squashed, and connected the interface, and the utils seemed functional [ no errors ].
> 
> If you want to remove all audit logs then you would have to add the other two mentioned above, and it looks like perhaps `network-control` too.
> 
> I don't think anything is required on the content snap.
> 
> I suspect that the nvidia-assemble snap would bit a bit more tricky to get working with standard builtin interfaces, because of the udev access. I'd more more than happy to work with you getting nvidia-assemble working without devmode, because we are keen use nvidia support. Shall I open a bug about it over in https://github.com/xnox/nvidia-assemble for discussion ?

yes please. My attempts at creating new interfaces so far have been futile, i believe i am missing some device confinment to actually expose the devices in question. I am also pondering how to achieve the same results with less effort - for example I am considering to hack pc-kernel to have stub nvidia.ko mentioned in the modules.dep with obsolute paths pointing at where nvidia-assemble will create the .ko at runtime, and probably exclude nouveau driver from the pc-kernel snap altogether (as it is rarely desired). But I haven't had any contacts so far with anybody trying to use these things or deploy them. So anyone to ping ideas and changes with is awesome.

**Comment by xnox** [comment]
@jocado I have added the above mentioned plugs and things do seem to work nicely for me on classic - which at least validates that graphics-core22-samples packaging is done correctly. To test on classic i did this:

1) I am on Ubuntu 22.04 LTS desktop laptop with nvidia gpu
2) Opened gnome shell search to find "Additional Drivers" and select nvidia-driver-515-server there
3) This installed and configured nvidia 515-server drivers like the ones we are trying to have on core. I then did reboot, as my kernel was out of date.
4) install / refresh graphics-core22-samples and connect all the plugs it has
5) on Ubuntu desktop as a regular user I was able to run graphics-core22-samples.deviceQuery graphics-core22-samples.bandwidthTest graphics-core22-samples.eglinfo just fine. The display tests didn't work - i guess it may need further plugs to get working. But at least it means that with classic confinement (which does export addition things from the host) things mostly work confined. So I think graphics-core22-samples is now in a much better shape.

**Comment by jocado** [comment]
Great - confirmed working here without devmode too on UC :+1: 

I notice that these plugs don't auto connect:
- hardware-observe
- kernel-module-observe

I'm used to a brand store, not the public one, so I don't know if it differs, but you may be able set those plugs to auto-connect in the store interface.
It didn't seem to effect functionality, but if it reduces kernel audit messages it's probably worth doing.

**Comment by xnox** [comment]
I don't think I can just autoconnect them :-) in brand store one can sign an assertion to autoconnect those.
